server:
  port: 8980
  servlet:
    context-path: /auth

spring:
  profiles:
    active: dev

jwt:
  secret: 46294A404E635266556A586E327235753778214125442A472D4B615064536756
  expiration: 36000000

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${POSTGRES_PASSWORD:root}
    username: ${POSTGRES_USERNAME:root}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:database}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
