server:
  port: 5555
  servlet:
    context-path: /gateway

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: lb://core-service/
          predicates:
            - Path=/core/**
        - id: cart-service-specific-path
          uri: lb://cart-service/
          predicates:
            - Path=/cart/v1/api/cart/generate_uuid
        - id: cart-service-general
          uri: lb://cart-service/
          predicates:
            - Path=/cart/**
          filters:
            - CartFilter
        - id: order-service
          uri: lb://order-service/
          predicates:
            - Path=/order/**
          filters:
            - TokenAuthenticationFilter
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: auth-service
          uri: lb://auth-service/
          predicates:
            - Path=/auth/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            '': TRACE

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

jwt:
  secret: 46294A404E635266556A586E327235753778214125442A472D4B615064536756
