server:
  port: 8090
  servlet:
    context-path: /cart

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: cart-service

integrations:
  core-service:
    url: http://${CORE_HOST:localhost}:${CORE_PORT:8080}/core
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
