server:
  port: 8090
  servlet:
    context-path: /cart

spring:
  profiles:
    active: dev

#management:
#  health:
#    circuitbreakers:
#      enabled: true
#  endpoints:
#    web:
#      exposure:
#        include: *
#  endpoint:
#    health:
#      show-details: always


#resilience4j:
#  circuitbreaker:
#    instances:
#      inventory:
#        registerHealthIndicator: true
#        eventConsumerBufferSize: 10
#        slidingWindowType: COUNT_BASED
#        slidingWindowSize: 5
#        failureRateThreshold: 50
#        waitDurationInOpenState: 5s
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true


---

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: cart-service

integrations:
  core-service:
    url: http://${CORE_HOST:localhost}:${CORE_PORT:8080}/core
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
