server:
  port: 8080
  servlet:
    context-path: /core
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/database
  liquibase:
    change-log: migration/db-changelog.sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
