server:
  port: 5555
  servlet:
    context-path: /gateway
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowedHeaders: "*"
      routes:
        - id: core-service-admin
          uri: lb://core-service/
          predicates:
            - Path=/core/v1/api/core/products
            - Method=POST
          filters:
            - TokenAuthenticationFilter
#        - id: core-service-swagger
#          uri: lb://core-service/
#          predicates:
#            - Path=/core/swagger-ui/**
#          filters:
#            - TokenAuthenticationFilter
        - id: core-service
          uri: lb://core-service/
          predicates:
            - Path=/core/**
        - id: cart-service-specific-path
          uri: lb://cart-service/
          predicates:
            - Path=/cart/v1/api/cart/generate_uuid
#        - id: cart-service-swagger
#          uri: lb://cart-service/
#          predicates:
#            - Path=/cart/swagger-ui/**
#          filters:
#            - TokenAuthenticationFilter
        - id: cart-service-general
          uri: lb://cart-service/
          predicates:
            - Path=/cart/**
          filters:
            - CartFilter
#        - id: auth-service-swagger
#          uri: lb://auth-service/
#          predicates:
#            - Path=/auth/swagger-ui/**
#          filters:
#            - TokenAuthenticationFilter
        - id: auth-service
          uri: lb://auth-service/
          predicates:
            - Path=/auth/**
        - id: order-service
          uri: lb://order-service/
          predicates:
            - Path=/order/**
          filters:
            - TokenAuthenticationFilter
        - id: review-service
          uri: lb://review-service/
          predicates:
            - Path=/review/**
#        - id: discovery-server
#          uri: http://eureka-service:8761
#          predicates:
#            - Path=/eureka/web
#          filters:
#            - SetPath=/
        - id: discovery-server-static
          uri: http://eureka-service:8761
          predicates:
            - Path=/eureka/**
          filters:
            - SetPath=/


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            '': TRACE

jwt:
  secret: 46294A404E635266556A586E327235753778214125442A472D4B615064536756

---

spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---

spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
