server:
  port: 5555
  servlet:
    context-path: /gateway
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - PATCH
            allowedHeaders: "*"
      routes:
        - id: core-service-admin
          uri: lb://core-service/
          predicates:
            - Path=/core-service/products
            - Method=POST
          filters:
            - StripPrefix=1
            - PrefixPath=/core/v1/api
            - TokenAuthenticationFilter
        - id: core-service
          uri: lb://core-service/
          predicates:
            - Path=/core-service/products/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core/v1/api
        - id: core-service-swagger
          uri: lb://core-service/
          predicates:
            - Path=/core-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/core
        - id: cart-service-specific-path
          uri: lb://cart-service/
          predicates:
            - Path=/cart-service/cart/generate_uuid
          filters:
            - StripPrefix=1
            - PrefixPath=/cart/v1/api
        - id: cart-service-general
          uri: lb://cart-service/
          predicates:
            - Path=/cart-service/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart/v1/api
            - CartFilter
        - id: cart-service-swagger
          uri: lb://cart-service/
          predicates:
            - Path=/cart-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/cart
        - id: auth-service
          uri: lb://auth-service/
          predicates:
            - Path=/auth-service/**
          filters:
            - StripPrefix=1
            - PrefixPath=/auth/v1/api
        - id: auth-service-swagger
          uri: lb://auth-service/
          predicates:
            - Path=/auth/swagger-ui/**
        - id: order-service
          uri: lb://order-service/
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/order/v1/api
            - TokenAuthenticationFilter
        - id: order-service-swagger
          uri: lb://order-service/
          predicates:
            - Path=/order/swagger-ui/**
        - id: review-service
          uri: lb://review-service/
          predicates:
            - Path=/review/**
          filters:
            - PrefixPath=/review/v1/api
        - id: review-service-swagger
          uri: lb://review-service/
          predicates:
            - Path=/review/**
        - id: discovery-server
          uri: http://eureka-service:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://eureka-service:8761
          predicates:
            - Path=/eureka/**
          filters:
            - SetPath=/


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            '': TRACE

jwt:
  secret: 46294A404E635266556A586E327235753778214125442A472D4B615064536756

---

spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---

spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
