server:
  port: 8090
  servlet:
    context-path: /cart

spring:
  application:
    name: cart-service

---

spring:
  config:
    activate:
      on-profile: dev
  redis:
    port: 6379
    host: localhost

integrations:
  core-service:
    url: http://localhost:8080/core
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
  inventory-service:
    url: http://localhost:8079/inventory
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---

spring:
  config:
    activate:
      on-profile: docker
  redis:
    port: 6379
    host: redis

integrations:
  core-service:
    url: http://core-service:8080/core
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
  inventory-service:
    url: http://inventory-service:8079/inventory
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
