server:
  port: 8080
  servlet:
    context-path: /core

spring:
  application:
    name: core-service
  liquibase:
    change-log: migration/db.changelog-master.yml
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: validate

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://localhost:5432/database

integrations:
  review-service:
    url: http://localhost:8778/review/v1/api/
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---

spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: root
    url: jdbc:postgresql://postgres:5432/database

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

integrations:
  review-service:
    url: http://review-service:8778/review/v1/api
    read-timeout: 10000
    write-timeout: 5000
    connect-timeout: 5000
