eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761

---

spring:
  config:
    activate:
      on-profile: dev

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

---

spring:
  config:
    activate:
      on-profile: docker

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
